---
- name: Get Arista EOS Running Configuration
  hosts: atladmin
  gather_facts: false
  connection: ansible.netcommon.network_cli

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: arista.eos.eos
    ansible_become: true
    ansible_become_method: enable

  tasks:
    - name: Run show running-config command
      arista.eos.eos_command:
        commands: 
          - show running | i snmp
      register: running_config_output

    - name: Display the running configuration
      ansible.builtin.debug:
        msg: "{{ running_config_output.stdout[0] }}"
